// AuthActions
export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILS = 'LOGIN_USER_FAILS'
export const LOGIN_USER = 'LOGIN_USER'

// EmployeeActions
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
export const EMPLOYEES_FECTH_SUCCESS = 'EMPLOYEES_FECTH_SUCCESS'
export const EMPLOYEE_SAVE_SUCCESS = 'EMPLOYEE_SAVE_SUCCESS'
